name: Deploy ke Hosting

on:
  push:
    branches:
      - main # jalan setiap push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # sesuaikan dengan hosting

      - name: Install dependencies via Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy ke server via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ # sesuaikan folder hosting
